name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  Run:
    name: Version
    uses: atls/shared/.github/workflows/version.yaml@master
    permissions: write-all
